service: aws-wisecaller-workingHrs-service

frameworkVersion: '2'
useDotenv: true
configValidationMode: warn
plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
package:
  patterns:
  - 'env.dev'
  - '!node_modules'
functions:
  api:
    handler: bin/handler.api
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY